---
title: "Balls from bag"
format:
  html:
    df-print: paged
execution:
  warning: false
---

```{r}
#| output: false
library(tidyverse)
```

## The question

-   **Knowledge base**:

    -   Imagine an urn that contains 1 Blue ball and 3 White balls (`BWWW`).

    -   We draw 3 balls with replacement. This means after each draw, we put the ball back in. [i.i.d.]

-   **Query**:

    -   What is the probability of drawing the sequence Blue, then White, then Blue (`BWB`)?

## Create sample space

```{r}
expand_grid(
  D1_B1 = c(TRUE, FALSE), D1_B2 = c(TRUE, FALSE), D1_B3 = c(TRUE, FALSE), D1_B4 = c(TRUE, FALSE),
  D2_B1 = c(TRUE, FALSE), D2_B2 = c(TRUE, FALSE), D2_B3 = c(TRUE, FALSE), D2_B4 = c(TRUE, FALSE),
  D3_B1 = c(TRUE, FALSE), D3_B2 = c(TRUE, FALSE), D3_B3 = c(TRUE, FALSE), D3_B4 = c(TRUE, FALSE))
```

```{r}
expand_grid(
  D1_B1 = c(TRUE, FALSE), D1_B2 = c(TRUE, FALSE), D1_B3 = c(TRUE, FALSE), D1_B4 = c(TRUE, FALSE),
  D2_B1 = c(TRUE, FALSE), D2_B2 = c(TRUE, FALSE), D2_B3 = c(TRUE, FALSE), D2_B4 = c(TRUE, FALSE),
  D3_B1 = c(TRUE, FALSE), D3_B2 = c(TRUE, FALSE), D3_B3 = c(TRUE, FALSE), D3_B4 = c(TRUE, FALSE)) %>% 
  mutate(
    # exactly one ball in first draw
    P1 = (  D1_B1 & !D1_B2 & !D1_B3 & !D1_B4 ) |
         ( !D1_B1 &  D1_B2 & !D1_B3 & !D1_B4 ) |
         ( !D1_B1 & !D1_B2 &  D1_B3 & !D1_B4 ) |
         ( !D1_B1 & !D1_B2 & !D1_B3 &  D1_B4 ),

    # exactly one ball in second draw
    P2 = (  D2_B1 & !D2_B2 & !D2_B3 & !D2_B4 ) |
         ( !D2_B1 &  D2_B2 & !D2_B3 & !D2_B4 ) |
         ( !D2_B1 & !D2_B2 &  D2_B3 & !D2_B4 ) |
         ( !D2_B1 & !D2_B2 & !D2_B3 &  D2_B4 ),

    # exactly one ball in third draw
    P3 = (  D3_B1 & !D3_B2 & !D3_B3 & !D3_B4 ) |
         ( !D3_B1 &  D3_B2 & !D3_B3 & !D3_B4 ) |
         ( !D3_B1 & !D3_B2 &  D3_B3 & !D3_B4 ) |
         ( !D3_B1 & !D3_B2 & !D3_B3 &  D3_B4 ),
    
    # exactly one ball in each draw
    E  = P1 & P2 & P3) %>%
  filter(E)
```


```{r}
expand_grid(
  D1_B1 = c(TRUE, FALSE), D1_B2 = c(TRUE, FALSE), D1_B3 = c(TRUE, FALSE), D1_B4 = c(TRUE, FALSE),
  D2_B1 = c(TRUE, FALSE), D2_B2 = c(TRUE, FALSE), D2_B3 = c(TRUE, FALSE), D2_B4 = c(TRUE, FALSE),
  D3_B1 = c(TRUE, FALSE), D3_B2 = c(TRUE, FALSE), D3_B3 = c(TRUE, FALSE), D3_B4 = c(TRUE, FALSE)) %>% 
  mutate(
    # exactly one ball in first draw
    P1 = (  D1_B1 & !D1_B2 & !D1_B3 & !D1_B4 ) |
         ( !D1_B1 &  D1_B2 & !D1_B3 & !D1_B4 ) |
         ( !D1_B1 & !D1_B2 &  D1_B3 & !D1_B4 ) |
         ( !D1_B1 & !D1_B2 & !D1_B3 &  D1_B4 ),

    # exactly one ball in second draw
    P2 = (  D2_B1 & !D2_B2 & !D2_B3 & !D2_B4 ) |
         ( !D2_B1 &  D2_B2 & !D2_B3 & !D2_B4 ) |
         ( !D2_B1 & !D2_B2 &  D2_B3 & !D2_B4 ) |
         ( !D2_B1 & !D2_B2 & !D2_B3 &  D2_B4 ),

    # exactly one ball in third draw
    P3 = (  D3_B1 & !D3_B2 & !D3_B3 & !D3_B4 ) |
         ( !D3_B1 &  D3_B2 & !D3_B3 & !D3_B4 ) |
         ( !D3_B1 & !D3_B2 &  D3_B3 & !D3_B4 ) |
         ( !D3_B1 & !D3_B2 & !D3_B3 &  D3_B4 ),
    
    # exactly one ball in each draw
    E  = P1 & P2 & P3) %>%
  filter(E) %>%
  mutate(
    # first draw is B (B1 is B in BWWW bag)
    D1_B = D1_B1 == TRUE,

    # second draw is W (B2, B3, and B4 are W in BWWW bag)
    D2_W = D2_B2 == TRUE | D2_B3 == TRUE | D2_B4 == TRUE, 

    # third draw is B (B1 is B in BWWW bag)
    D3_B = D3_B1 == TRUE,

    # BWB event
    H  = D1_B & D2_W & D3_B) %>%
  filter(E) %>%
  pull(H) %>%
  mean()
```

```{r}
dprop <- function(b, w) {
  n <- b + w
  return(b / n)
}

dprop(1, 3) * (1 - dprop(1, 3)) * dprop(1, 3)
```

```{r}
bag <- c("B1", "W1", "W2", "W3")

# Step 1: Create the sample space using Draw-Ball variables
ss <- expand_grid(
  D1 = bag,
  D2 = bag,
  D3 = bag
)
```

```{r}
# Step 2: Define the BWB event
ss %>%
  mutate(
    H = (D1 == "B1") & (D2 %in% c("W1", "W2", "W3")) & (D3 == "B1")
  ) %>%
  pull(H) %>%
  mean()
```

