<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The causal data science pipeline in practice</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="dliotsiou_causality_DSF_demo_files/libs/clipboard/clipboard.min.js"></script>
<script src="dliotsiou_causality_DSF_demo_files/libs/quarto-html/quarto.js"></script>
<script src="dliotsiou_causality_DSF_demo_files/libs/quarto-html/popper.min.js"></script>
<script src="dliotsiou_causality_DSF_demo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="dliotsiou_causality_DSF_demo_files/libs/quarto-html/anchor.min.js"></script>
<link href="dliotsiou_causality_DSF_demo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="dliotsiou_causality_DSF_demo_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="dliotsiou_causality_DSF_demo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="dliotsiou_causality_DSF_demo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="dliotsiou_causality_DSF_demo_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The causal data science pipeline in practice</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- Demo using example of a retail problem. -->
<p>Let’s say retailer offers a premium monthly subscription programme: * further discounts on mainline shopping, and * benefits with this company’s other verticals (e.g.&nbsp;clothing line; cafe; etc).</p>
<p>Question: <strong>What is the effect of subscribing to this programme on mainline spend at this company?</strong><br>
* Synthetic data</p>
<section id="the-causal-pipeline" class="level1">
<h1>The causal pipeline</h1>
<section id="draw-causal-dag" class="level2">
<h2 class="anchored" data-anchor-id="draw-causal-dag">1. Draw causal DAG</h2>
<p>First, map out the relevant variables * <strong>X: subscribing or not</strong> * <strong>Y: spend</strong> * Other relevant causes? Sit down and think with team and stakeholders, think of all potential causes and causal paths that could affect whether subscribe and/or spend? - <strong>disposable income:</strong> high income might spend more and not care about discounts/ benefits of the programme - <strong>age:</strong> depending on age, different needs, life stages, mindsets, e.g.&nbsp;20s, 40s, 70s. - <strong>family size:</strong> if someone with a large family, higher volume of shopping, might spend more, and might see value in subscribing and discounts etc benefits - <strong>interest in verticals:</strong> if are interested other verticals, might find programme more appealing. - <strong>… more:</strong> realistically will have many more relevant, but stop here in the interest of time.</p>
<p>Draw all this in causal DAG as you go, with all possible arrows, and visualise it.</p>
<p>Python <a href="https://github.com/py-why/dowhyhttps://github.com/py-why/dowhy">DoWhy</a> syntax:</p>
<div id="d870edd9-85a6-4225-93c8-de787b6e8526" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:19.781086Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:19.780284Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:23.931986Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:23.928571Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:19.780982Z&quot;}" data-tags="[]" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> dowhy</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dowhy <span class="im">import</span> CausalModel</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="a103a9fe-4368-4237-a36b-40a657611feb" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:23.936583Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:23.936177Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:23.950188Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:23.948945Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:23.936518Z&quot;}" data-tags="[]" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dowhy.__version__ <span class="co"># not latest: Date: Sep 05, 2023 Version: v0.10.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>'0.8'</code></pre>
</div>
</div>
<div id="2349d5e1-787a-48c1-b23a-b07c74905b95" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:23.954181Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:23.953790Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:24.019745Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:24.017625Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:23.954127Z&quot;}" data-tags="[]" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Digraph Syntax</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>causal_graph <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="st">digraph {</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="st">age -&gt; disp_income; age -&gt; vertical_interest; age -&gt; family_size;</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="st">age -&gt; premium_sub; age -&gt; post_spend; </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="st">disp_income -&gt; vertical_interest; disp_income -&gt; family_size;</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="st">disp_income -&gt; premium_sub; disp_income -&gt; post_spend;</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="st">family_size -&gt; vertical_interest; family_size -&gt; premium_sub;</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="st">family_size -&gt; post_spend;</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="st">vertical_interest-&gt; premium_sub; vertical_interest-&gt; post_spend;</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="st">premium_sub -&gt; post_spend;</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="st">}</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To define a <code>CausalModel</code> object in DoWhy and then identify estimands, first need a dataframe with columns : DAG variables, no need for data</p>
<div id="cc306f50-f1a2-43fd-a495-6955934acfdb" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:24.024604Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:24.024176Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:24.053014Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:24.050816Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:24.024530Z&quot;}" data-tags="[]" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="21a9aa46-18a0-43d5-927c-c1db9e2fa8ed" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:24.057353Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:24.056254Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:24.137092Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:24.135063Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:24.057276Z&quot;}" data-tags="[]" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> pd.DataFrame(columns<span class="op">=</span>[<span class="st">'age'</span>, <span class="st">'disp_income'</span>, <span class="st">'family_size'</span>, <span class="st">'premium_sub'</span>, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">'post_spend'</span>, <span class="st">'vertical_interest'</span>])</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df_model.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">disp_income</th>
<th data-quarto-table-cell-role="th">family_size</th>
<th data-quarto-table-cell-role="th">premium_sub</th>
<th data-quarto-table-cell-role="th">post_spend</th>
<th data-quarto-table-cell-role="th">vertical_interest</th>
</tr>
</thead>
<tbody>
</tbody>
</table>

</div>
</div>
</div>
<div id="4e44d43c-e233-48a3-8af6-d8fb2b60a3df" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:24.140791Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:24.140264Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:25.245572Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:25.244016Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:24.140704Z&quot;}" data-tags="[]" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a CausalModel object in DoWhy, indicate treatment &amp; outcome</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>model<span class="op">=</span> CausalModel(data<span class="op">=</span>df_model, <span class="co"># data columns</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>        graph<span class="op">=</span>causal_graph, <span class="co"># DAG</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        treatment<span class="op">=</span><span class="st">'premium_sub'</span>, <span class="co"># cause of interest, X</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        outcome<span class="op">=</span><span class="st">'post_spend'</span>) <span class="co"># outcome, Y</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>model.view_model()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dliotsiou_causality_DSF_demo_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Other ways to visualise DAG: * networkX Python library * <a href="https://www.dagitty.net/dags.html#">DAGitty</a> interactive web tool</p>
<p><strong>We now have the DAG, can run identification on it to see what should adjust for.</strong></p>
</section>
</section>
<section id="identification" class="level1">
<h1>2. Identification</h1>
<div id="427b0ffc-1cfb-47e9-a471-4ac681d1ab35" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:25.248382Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:25.248032Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:25.284658Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:25.283157Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:25.248329Z&quot;}" data-tags="[]" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify the causal effect</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>estimands <span class="op">=</span> model.identify_effect(proceed_when_unidentifiable<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(estimands)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
      d                                                                       
──────────────(Expectation(post_spend|vertical_interest,disp_income,family_siz
d[premium_sub]                                                                

       
e,age))
       
Estimand assumption 1, Unconfoundedness: If U→{premium_sub} and U→post_spend then P(post_spend|premium_sub,vertical_interest,disp_income,family_size,age,U) = P(post_spend|premium_sub,vertical_interest,disp_income,family_size,age)

### Estimand : 2
Estimand name: iv
No such variable(s) found!

### Estimand : 3
Estimand name: frontdoor
No such variable(s) found!
</code></pre>
</div>
</div>
<p><strong>We now know what variables we should adjust for, can proceed to estimation.</strong></p>
</section>
<section id="before-estimation-the-data" class="level1">
<h1>Before estimation: The data</h1>
<p>Having drawn out our view of how the world works (the DAG), and figured out via identification the available estimands (backdoor here), and what we should adjust for, we now look at our data to see whether it contains good measures for all variables in our minimal adjustment set. Construct valilidity, operationalisation.</p>
<p>Having inspected our data, let’s say we find it does contain adequate-looking measures (or proxies) for all variables in the minimal deconfounding set<em>: </em> <strong>disposable income</strong>: a binary <strong><code>affluence</code></strong> segementation * <strong>family size</strong>: number of children under the age of 18 at that househould, <strong><code>num_child_u18</code></strong> * <strong>interest in vericals</strong>: <strong><code>vertical_frac</code></strong>, % of previous spend on verticals – being an existing customer may indicate continued interest in the future, in proportion to previous spend * <strong>age</strong>: measured in years in column <strong><code>age</code></strong></p>
<p>(* If a dataset does <em>not</em> contain good measures for all varaibles in the min. deconfounding set: the causal effect of interest is <em>not identifiable</em> based on this data. Cannot make causal claims, as cannot remove confounding. So either try to get data on unobserved variables/ do not make causal claims/ try sensitivity analysis to bound size of remaining bias from these unmeasured confounders, requires extra assumptions – more in the validation/refutation section below)</p>
<p>The data also contains these columns for X and Y: - <strong>X</strong> measured in <strong><code>premium_sub</code>:</strong> 1 for customers who join the premium subscription, 0 for those who don’t - <strong>Y</strong> measured in <strong><code>post_spend</code>:</strong> aggregate spend (in £) in the 12 months after the window of opportunity to subscribe to the scheme or not, for each given window.</p>
<p>We now load &amp; inspect our data: * Columns for the above causal variables. * One row per household – max 1 subscription possible per household:</p>
<div id="c3b30c89-4407-4a2c-96ee-199c6b3758a6" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:25.290407Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:25.290050Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:25.344244Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:25.343115Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:25.290350Z&quot;}" data-tags="[]" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'full_data.csv'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">affluence</th>
<th data-quarto-table-cell-role="th">num_child_u18</th>
<th data-quarto-table-cell-role="th">vertical_frac</th>
<th data-quarto-table-cell-role="th">post_spend</th>
<th data-quarto-table-cell-role="th">premium_sub</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>31</td>
<td>1</td>
<td>1</td>
<td>0.11</td>
<td>1723.96</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>76</td>
<td>0</td>
<td>0</td>
<td>0.02</td>
<td>2144.16</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>50</td>
<td>0</td>
<td>1</td>
<td>0.15</td>
<td>457.00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>42</td>
<td>0</td>
<td>5</td>
<td>0.05</td>
<td>7373.70</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>48</td>
<td>1</td>
<td>6</td>
<td>0.11</td>
<td>742.11</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Now, make variable measure names in dataset match variable names in the DAG – <code>CausalModel</code>’s <code>graph</code> parameter, replace variable names by their measure names:</p>
<div id="7474727f-0be4-436c-a698-122a23ad0b04" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:25.348171Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:25.347811Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:26.483940Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:26.482723Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:25.348119Z&quot;}" data-tags="[]" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify the causal effect</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Digraph Syntax</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>causal_graph <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="st">digraph {</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="st">age -&gt; affluence; age -&gt; vertical_frac; age -&gt; num_child_u18;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="st">age -&gt; premium_sub; age -&gt; post_spend;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="st">affluence -&gt; vertical_frac; affluence -&gt; num_child_u18;</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="st">affluence -&gt; premium_sub; affluence -&gt; post_spend;</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="st">num_child_u18 -&gt; vertical_frac; num_child_u18 -&gt; premium_sub;</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="st">num_child_u18 -&gt; post_spend;</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="st">vertical_frac -&gt; premium_sub; vertical_frac -&gt; post_spend;</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="st">premium_sub -&gt; post_spend;</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="st">}</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>model<span class="op">=</span> CausalModel(data<span class="op">=</span>df, <span class="co"># actual dataset now</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>        graph<span class="op">=</span>causal_graph,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>        treatment<span class="op">=</span><span class="st">'premium_sub'</span>,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>        outcome<span class="op">=</span><span class="st">'post_spend'</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>model.view_model()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dliotsiou_causality_DSF_demo_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="ef58e8a4-fcea-4ab4-b3e5-3aa66504b947" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:26.486566Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:26.486227Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:26.513386Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:26.511278Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:26.486515Z&quot;}" data-tags="[]" data-execution_count="11">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>estimands <span class="op">=</span> model.identify_effect()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(estimands)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
      d                                                                       
──────────────(Expectation(post_spend|num_child_u18,affluence,age,vertical_fra
d[premium_sub]                                                                

   
c))
   
Estimand assumption 1, Unconfoundedness: If U→{premium_sub} and U→post_spend then P(post_spend|premium_sub,num_child_u18,affluence,age,vertical_frac,U) = P(post_spend|premium_sub,num_child_u18,affluence,age,vertical_frac)

### Estimand : 2
Estimand name: iv
No such variable(s) found!

### Estimand : 3
Estimand name: frontdoor
No such variable(s) found!
</code></pre>
</div>
</div>
<p><strong>Now that we’ve found adequate measures in our data for all variables in the minimal deconfounding set, and used this data of these measures in our DAG and identification step, we can do estimation.</strong></p>
</section>
<section id="estimation" class="level1">
<h1>3. Estimation</h1>
<p>DoWhy implements some estimation methods:</p>
<div id="e87db430-0ead-435b-aed2-755e8ad2326b" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:26.516052Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:26.515708Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.109037Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.107574Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:26.516005Z&quot;}" data-tags="[]" data-execution_count="12">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>estimate <span class="op">=</span> model.estimate_effect(estimands,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                                 method_name<span class="op">=</span><span class="st">"backdoor.linear_regression"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                                 effect_modifiers<span class="op">=</span> [],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                 confidence_intervals<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                                 test_significance<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(estimate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>linear_regression
{'control_value': 0, 'treatment_value': 1, 'test_significance': True, 'evaluate_effect_strength': False, 'confidence_intervals': True, 'target_units': 'ate', 'effect_modifiers': []}
*** Causal Estimate ***

## Identified estimand
Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
      d                                                                       
──────────────(Expectation(post_spend|num_child_u18,affluence,age,vertical_fra
d[premium_sub]                                                                

   
c))
   
Estimand assumption 1, Unconfoundedness: If U→{premium_sub} and U→post_spend then P(post_spend|premium_sub,num_child_u18,affluence,age,vertical_frac,U) = P(post_spend|premium_sub,num_child_u18,affluence,age,vertical_frac)

## Realized estimand
b: post_spend~premium_sub+num_child_u18+affluence+age+vertical_frac
Target units: ate

## Estimate
Mean value: 555.9003475909958
p-value: [2.60024816e-29]
95.0% confidence interval: [[459.14064275 652.66005243]]
</code></pre>
</div>
</div>
<div id="94b7b0f5-3422-4abe-b84d-1adf42423e09" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:27.111754Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:27.111402Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.126130Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.124683Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:27.111702Z&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>estimate.interpret()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Increasing the treatment variable(s) [premium_sub] from 0 to 1 causes an increase of 555.9003475909958 in the expected value of the outcome [post_spend], over the data distribution/population represented by the dataset.</code></pre>
</div>
</div>
<p>So joining this premium subscription programme has a causal effect of spending £555.9 more at this retailer over the next 12 months. (Synthetic data)</p>
<section id="standard-python-libraries-also-apply-for-estimation" class="level3">
<h3 class="anchored" data-anchor-id="standard-python-libraries-also-apply-for-estimation">Standard Python libraries also apply for estimation</h3>
<p>Can use statsmodels, or sklearn (tree-based, with partial dependence plots for coefficients equivalents).</p>
<p>E.g. statsmodels OLS. We get the exact same results as with the DoWhy OLS estimation.</p>
<div id="e5eebf57-621f-45b4-898f-616757f63d5a" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:27.128481Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:27.128156Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.142798Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.138786Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:27.128434Z&quot;}" data-tags="[]" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="ecaf7d2d-4ef1-4ddd-972a-3110d6561ecb" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:27.145129Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:27.144792Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.223746Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.222112Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:27.145082Z&quot;}" data-tags="[]" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>reg_model_all <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'post_spend ~ premium_sub + vertical_frac + age + affluence + num_child_u18'</span>, data <span class="op">=</span> df)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>ols_all <span class="op">=</span> reg_model_all.fit()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Effect of premium sub: </span><span class="ch">\n</span><span class="st"> coeff: </span><span class="ch">\t</span><span class="st">'</span>, ols_all.params[<span class="st">'premium_sub'</span>], </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="st">'</span><span class="ch">\n</span><span class="st"> p value: </span><span class="ch">\t</span><span class="st">'</span>, ols_all.pvalues.loc[<span class="st">'premium_sub'</span>], </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>     <span class="st">'</span><span class="ch">\n</span><span class="st"> 95% C.I.s: </span><span class="ch">\t</span><span class="st">'</span>, ols_all.conf_int(alpha <span class="op">=</span> <span class="fl">0.05</span>).loc[<span class="st">'premium_sub'</span>].values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect of premium sub: 
 coeff:      555.9003475909925 
 p value:    2.6002481581378363e-29 
 95% C.I.s:      [459.14064275 652.66005243]</code></pre>
</div>
</div>
</section>
<section id="confounding-bias-simpsons-paradox" class="level2">
<h2 class="anchored" data-anchor-id="confounding-bias-simpsons-paradox"><em>Confounding bias, Simpson’s paradox</em></h2>
<p>In this case, we had to control for everything. <em>Not</em> a general rule: * must not control for colliders, bias (more below); * computationally inefficient to control for confounders not in the minimal set</p>
<p>E.g. if we don’t have data for some/ all of the varablies in the minimal deconfounding set, cannot adjust for them in the estimation model. Some confounding bias will remain, effect not guaranteed to be the same or close to the unbiased one.</p>
<section id="some-scenarios" class="level4">
<h4 class="anchored" data-anchor-id="some-scenarios">Some scenarios:</h4>
</section>
<section id="a.-unobserved-all-confounders" class="level4">
<h4 class="anchored" data-anchor-id="a.-unobserved-all-confounders"><em>a. Unobserved: all confounders</em></h4>
<div id="aa8e2a87-8a4e-4ff3-bb3e-75293567cdaa" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:27.227358Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:27.226526Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.255336Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.253654Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:27.227303Z&quot;}" data-tags="[]" data-execution_count="16">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unadjusted estimate is confounded</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>reg_model <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'post_spend ~ premium_sub'</span>, data <span class="op">=</span> df)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>ols <span class="op">=</span> reg_model.fit()</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ols.params[<span class="st">"premium_sub"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1097.9085781224944</code></pre>
</div>
</div>
<p>Estimate way off, overestimates effect by almost 2x – confounding bias is very large.</p>
</section>
<section id="b.-unobserved-age-num_child_u18" class="level4">
<h4 class="anchored" data-anchor-id="b.-unobserved-age-num_child_u18"><em>b. Unobserved: age, num_child_u18</em></h4>
<div id="43bcc7a5-c68e-42bf-9879-a98d93faf127" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:27.257949Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:27.257600Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.299434Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.294881Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:27.257886Z&quot;}" data-tags="[]" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>reg_model_some <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'post_spend ~ premium_sub + vertical_frac + affluence'</span>, data <span class="op">=</span> df)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ols_some <span class="op">=</span> reg_model_some.fit()</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Effect of premium sub: </span><span class="ch">\n</span><span class="st"> coeff: </span><span class="ch">\t</span><span class="st">'</span>, ols_some.params[<span class="st">'premium_sub'</span>], </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">'</span><span class="ch">\n</span><span class="st"> p value: </span><span class="ch">\t</span><span class="st">'</span>, ols_some.pvalues.loc[<span class="st">'premium_sub'</span>], </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>     <span class="st">'</span><span class="ch">\n</span><span class="st"> 95% C.I.s: </span><span class="ch">\t</span><span class="st">'</span>, ols_some.conf_int(alpha <span class="op">=</span> <span class="fl">0.05</span>).loc[<span class="st">'premium_sub'</span>].values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect of premium sub: 
 coeff:      642.2524825036953 
 p value:    1.5286533516181535e-39 
 95% C.I.s:      [546.82690115 737.67806386]</code></pre>
</div>
</div>
<p>Estimate is off again, now by a factor of 1.15.</p>
</section>
<section id="c.-unobserved-age-num_child_u18-affluence" class="level4">
<h4 class="anchored" data-anchor-id="c.-unobserved-age-num_child_u18-affluence"><em>c.&nbsp;Unobserved: age, num_child_u18, <strong>&amp; affluence</strong></em></h4>
<div id="0abc1002-5ed7-41d8-a7cc-3092210d3bd5" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:27.302206Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:27.301857Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:27.349664Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:27.348209Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:27.302159Z&quot;}" data-tags="[]" data-execution_count="18">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>reg_model_some2 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'post_spend ~ premium_sub + vertical_frac'</span>, data <span class="op">=</span> df)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ols_some2 <span class="op">=</span> reg_model_some2.fit()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Effect of premium sub: </span><span class="ch">\n</span><span class="st"> coeff: </span><span class="ch">\t</span><span class="st">'</span>, ols_some2.params[<span class="st">'premium_sub'</span>], </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">'</span><span class="ch">\n</span><span class="st"> p value: </span><span class="ch">\t</span><span class="st">'</span>, ols_some2.pvalues.loc[<span class="st">'premium_sub'</span>], </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>     <span class="st">'</span><span class="ch">\n</span><span class="st"> 95% C.I.s: </span><span class="ch">\t</span><span class="st">'</span>, ols_some2.conf_int(alpha <span class="op">=</span> <span class="fl">0.05</span>).loc[<span class="st">'premium_sub'</span>].values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect of premium sub: 
 coeff:      1097.9103163047 
 p value:    6.418127339061289e-168 
 95% C.I.s:      [1020.87911911 1174.9415135 ]</code></pre>
</div>
</div>
<p>Estimate is way off again, again by almost a factor of 2.</p>
</section>
</section>
<section id="collider-bias-berksons-paradox" class="level2">
<h2 class="anchored" data-anchor-id="collider-bias-berksons-paradox"><em>Collider bias, Berkson’s paradox</em></h2>
<ul>
<li>The case against throwing all variables as inputs into the model.</li>
<li>Same DAG.</li>
<li>Now want the effect of <em>age</em> on spend, and we still have data on the other variables.</li>
<li>Now: no confounders, no arrows into age, no common causes possible between it and spend. Thus, regressing <code>post_spend</code> only on <code>age</code> would give the correct causal estimate.</li>
</ul>
<div id="55a3420f-5cca-4f26-ad36-a8adccb60dec" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:40.325009Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:40.324098Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.332644Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.330359Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:40.324881Z&quot;}" data-tags="[]" data-execution_count="20">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model_age<span class="op">=</span> CausalModel(data<span class="op">=</span>df,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>        graph<span class="op">=</span>causal_graph,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>        treatment<span class="op">=</span><span class="st">'age'</span>,<span class="co"># different X now</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>        outcome<span class="op">=</span><span class="st">'post_spend'</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>model_age.view_model()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dliotsiou_causality_DSF_demo_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="885c7c98-9ee5-4a33-a8ea-f2dd3ab98fd9" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.336143Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.335788Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.438903Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.437344Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.336092Z&quot;}" data-tags="[]" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Identify</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>estimands_age <span class="op">=</span> model_age.identify_effect()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Estimate</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>estimate_age <span class="op">=</span> model_age.estimate_effect(estimands_age,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                                 method_name<span class="op">=</span><span class="st">"backdoor.linear_regression"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                                 confidence_intervals<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                                 test_significance<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(estimate_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>linear_regression
{'control_value': 0, 'treatment_value': 1, 'test_significance': True, 'evaluate_effect_strength': False, 'confidence_intervals': True, 'target_units': 'ate', 'effect_modifiers': []}
*** Causal Estimate ***

## Identified estimand
Estimand type: nonparametric-ate

### Estimand : 1
Estimand name: backdoor
Estimand expression:
  d                            
──────(Expectation(post_spend))
d[age]                         
Estimand assumption 1, Unconfoundedness: If U→{age} and U→post_spend then P(post_spend|age,,U) = P(post_spend|age,)

## Realized estimand
b: post_spend~age
Target units: ate

## Estimate
Mean value: 16.514473672870963
p-value: [4.48957132e-85]
95.0% confidence interval: [[14.86778215 18.1611652 ]]
</code></pre>
</div>
</div>
<p>What if we adjust for some of the other variables?</p>
<p>DAG shows there are 3 colliders: <code>premium_sub</code>, <code>vertical_frac</code>, and <code>num_child_u18</code> are colliders on the paths between <code>age</code> and <code>post_spend</code>. e.g.<br>
* <code>num_child_u18</code> is a collider on the path: <code>age</code> –&gt; <code>num_child_u18</code> &lt;– <code>affluence</code> –&gt; <code>post_spend</code> * <code>vertical_frac</code> is a collider on the path: <code>age</code> –&gt; <code>vertical_frac</code> &lt;– <code>num_child_u18</code> –&gt; <code>post_spend</code></p>
<p>If we adjust for any, or all, of them, we will introduce collider bias into the estimate. For example,</p>
<section id="a.-erroneously-adjust-for-all-colliders" class="level4">
<h4 class="anchored" data-anchor-id="a.-erroneously-adjust-for-all-colliders"><em>a. Erroneously adjust for ALL colliders</em></h4>
<div id="54a4ffcc-286b-401e-9e40-1cda04f1e06d" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.446236Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.445867Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.509997Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.508364Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.446185Z&quot;}" data-tags="[]" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ATE OF AGE on SPEND - erroneously adjust for ALL others, colliders</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>reg_age2 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'post_spend ~ age + premium_sub + vertical_frac + num_child_u18 '</span>, data <span class="op">=</span> df)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>ols_age2 <span class="op">=</span> reg_age2.fit()</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Effect of age: </span><span class="ch">\n</span><span class="st"> coeff: </span><span class="ch">\t</span><span class="st">'</span>, ols_age2.params[<span class="st">'age'</span>], </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">'</span><span class="ch">\n</span><span class="st"> p value: </span><span class="ch">\t</span><span class="st">'</span>, ols_age2.pvalues.loc[<span class="st">'age'</span>], </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>     <span class="st">'</span><span class="ch">\n</span><span class="st"> 95% C.I.s: </span><span class="ch">\t</span><span class="st">'</span>, ols_age2.conf_int(alpha <span class="op">=</span> <span class="fl">0.05</span>).loc[<span class="st">'age'</span>].values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect of age: 
 coeff:      13.523374963177083 
 p value:    7.789530825371502e-48 
 95% C.I.s:      [11.70485859 15.34189134]</code></pre>
</div>
</div>
<p>Substantially different, biased, estimate – 18% lower than the correct estimate of 16.5.</p>
</section>
<section id="b.-erroneously-adjust-for-some-colliders-unobserved-num_child_u18" class="level4">
<h4 class="anchored" data-anchor-id="b.-erroneously-adjust-for-some-colliders-unobserved-num_child_u18"><em>b. Erroneously adjust for SOME colliders: unobserved num_child_u18</em></h4>
<p>Assume the <code>num_child_u18</code> collider is unmeasured, adjust for all others which are measured.</p>
<div id="6772705e-bbed-4ab1-848b-5ad939634c24" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.518371Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.517889Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.581631Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.577959Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.518320Z&quot;}" data-tags="[]" data-execution_count="23">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ATE OF AGE on SPEND - erroneously adjust for ALL others, colliders</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>reg_age3 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'post_spend ~ age + premium_sub + vertical_frac '</span>, data <span class="op">=</span> df)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>ols_age3 <span class="op">=</span> reg_age3.fit()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Effect of age: </span><span class="ch">\n</span><span class="st"> coeff: </span><span class="ch">\t</span><span class="st">'</span>, ols_age3.params[<span class="st">'age'</span>], </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">'</span><span class="ch">\n</span><span class="st"> p value: </span><span class="ch">\t</span><span class="st">'</span>, ols_age3.pvalues.loc[<span class="st">'age'</span>], </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>     <span class="st">'</span><span class="ch">\n</span><span class="st"> 95% C.I.s: </span><span class="ch">\t</span><span class="st">'</span>, ols_age3.conf_int(alpha <span class="op">=</span> <span class="fl">0.05</span>).loc[<span class="st">'age'</span>].values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect of age: 
 coeff:      11.13673765674627 
 p value:    3.3131038736435847e-38 
 95% C.I.s:      [ 9.45186578 12.82160953]</code></pre>
</div>
</div>
<p>Biased estimate now 32.5% lower than the correct one.</p>
<p>So, naively using all/ as many as possible variables as inputs can result in very substantial bias! Don’t throw in everything and the kitchen sink.</p>
<p><strong>Overall, confounding bias (Simpson’s paradox) and/or collider bias (Berkson’s paradox) can lead to highly biased estimates.</strong></p>
<p>–</p>
<p>Going back to our original, correctly identified, unbiased estimate:</p>
<p><strong>We’ve found that joining this subscription programme causes additional future spending of £555.9 on average at this retailer over the next year. (Synthetic data).</strong></p>
<p><strong>Now we can proceed to validation, to check whether our DAG, and our whole estimate, are consistent with our data.</strong></p>
</section>
</section>
</section>
<section id="validation" class="level1">
<h1>4. Validation</h1>
<section id="a.-dag-vs.-data" class="level2">
<h2 class="anchored" data-anchor-id="a.-dag-vs.-data">4.A. DAG vs.&nbsp;data</h2>
<p>DAG - d-separation - (conditional) dependecies &amp; independencies. Must 1. <strong>DAG</strong>: apply d-separation, find what (conditional) independecies the DAG implies, if any. 2. <strong>vs.&nbsp;data</strong>: test if these (conditional) independecies all also exist in the data, standard statstistical tests.</p>
<section id="both-in-dowhy" class="level3">
<h3 class="anchored" data-anchor-id="both-in-dowhy">Both, in DoWhy</h3>
<p>DoWhy <code>refute_graph()</code> tests whether <strong>X ⊥ Y | Z</strong>, for all possible combinations of X, Y and Z.</p>
<p>Z is a set, parameter <code>k</code> below is the number of variables in it. So k max can be (num DAG variables - 2).</p>
<div id="07887261-5941-40e3-a979-00ff83294171" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.584038Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.583372Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.782828Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.781623Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.583989Z&quot;}" data-tags="[]" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DoWhy</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">5</span>)):</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    refuter_object <span class="op">=</span> model.refute_graph(k<span class="op">=</span>k, </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                                    independence_test <span class="op">=</span> {<span class="st">'test_for_continuous'</span>: <span class="st">'partial_correlation'</span>, </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                                                         <span class="st">'test_for_discrete'</span> : <span class="st">'conditional_mutual_information'</span>}) <span class="co">#Change k parameter to test conditional independence given different number of variables </span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(refuter_object)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>k=0
Method name for discrete data:conditional_mutual_information
Method name for continuous data:partial_correlation
Number of conditional independencies entailed by model:0
Number of independences satisfied by data:0
Test passed:True

k=1
Method name for discrete data:conditional_mutual_information
Method name for continuous data:partial_correlation
Number of conditional independencies entailed by model:0
Number of independences satisfied by data:0
Test passed:True

k=2
Method name for discrete data:conditional_mutual_information
Method name for continuous data:partial_correlation
Number of conditional independencies entailed by model:0
Number of independences satisfied by data:0
Test passed:True

k=3
Method name for discrete data:conditional_mutual_information
Method name for continuous data:partial_correlation
Number of conditional independencies entailed by model:0
Number of independences satisfied by data:0
Test passed:True

k=4
Method name for discrete data:conditional_mutual_information
Method name for continuous data:partial_correlation
Number of conditional independencies entailed by model:0
Number of independences satisfied by data:0
Test passed:True
</code></pre>
</div>
</div>
<p>This specific DAG implies: only (conditional) dependencies, no independence claims – nothing is d-separable from anything. So this DAG makes no strong claims of independence.</p>
</section>
<section id="dag-in-dagitty" class="level3">
<h3 class="anchored" data-anchor-id="dag-in-dagitty">DAG: in DAGitty…</h3>
<ul>
<li>If you’d like to see <em>which</em> (conditional) independencies the DAG implies, DAGitty lists all. But can’t load data into DAGitty web tool, so then …</li>
</ul>
</section>
<section id="vs.-the-data-in-dowhy" class="level3">
<h3 class="anchored" data-anchor-id="vs.-the-data-in-dowhy">… vs.&nbsp;the data: in DoWhy</h3>
<ul>
<li>Use DoWhy to test each of these against the data. (If any of these fail vs.&nbsp;the data, we will know <em>which part</em> of the DAG is wrong and so we should revisit.)</li>
</ul>
<p>Normally we’d only check the <strong>in</strong>dependence relationships found, but here there’s none – still, functionality shown below.</p>
<p>DoWhy’s Partial correlation implementation, tests whether X and Y are independent (uncorrelated) conditional on Z:</p>
<div id="14267d64-50ba-43fc-a610-3fddce644ca1" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.786070Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.785597Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.850840Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.849113Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.786022Z&quot;}" data-tags="[]" data-execution_count="25">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dowhy.utils.cit <span class="im">import</span> partial_corr</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>partial_corr(df, x<span class="op">=</span><span class="st">'vertical_frac'</span>, y<span class="op">=</span><span class="st">'post_spend'</span>, z<span class="op">=</span>[<span class="st">'affluence'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>{'n': 16796,
 'r': 0.042714942805828805,
 'CI95%': [array([0.028, 0.058])],
 'p-val': 0.0}</code></pre>
</div>
</div>
<div id="58954edf-7193-45e5-abe7-2258dfaee091" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.853762Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.853367Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.875880Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.874830Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.853703Z&quot;}" data-tags="[]" data-execution_count="26">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>partial_corr(df, x<span class="op">=</span><span class="st">'affluence'</span>, y<span class="op">=</span><span class="st">'post_spend'</span>, z<span class="op">=</span>[])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>{'n': 16796,
 'r': 0.21598236165125034,
 'CI95%': [array([0.202, 0.23 ])],
 'p-val': 0.0}</code></pre>
</div>
</div>
<p>Interpreting this output: * <code>n</code>: the number of rows in our data * <code>r</code>: the partial correlation coefficient between x and y, conditional on z. If z=[], empty set, unconditional independence test. Here: Non-0 correlation coefficients. * <code>CI95%</code>: the 95% confidence interval for <code>r</code>. * <code>p-val</code>: the p-value at the 5% significance level. If this is less than 0.05, we can reject the null hypothesis that x and y are independent conditional on z. Here, the p-value is 0.0 &lt; 0.05, which means there is a stastistically significant dependence i.e.&nbsp;correlation.</p>
<p><strong>So, we’ve found that our DAG is consistent with our data.</strong></p>
</section>
</section>
<section id="b-dowhy-final-estimate-vs.-data" class="level2">
<h2 class="anchored" data-anchor-id="b-dowhy-final-estimate-vs.-data">4.B DoWhy: Final estimate vs.&nbsp;data</h2>
<p>Estimate obtained from chosen estimation model (with inputs chosen based on 1. DAG; 2. identificaiton step) vs the data.</p>
<p>DoWhy offers several refuters for this.</p>
<p>E.g. these 3 refuters, per the DoWhy documentation:</p>
<ul>
<li>Does the estimated effect change significantly when we replace the given dataset with …
<ul>
<li>… bootstrapped samples from the same dataset? (<strong>Bootstrap Validation</strong>)</li>
<li>… a randomly selected subset? (<strong>Data Subsets Validation</strong>)</li>
</ul></li>
<li>Does the estimation method change its estimate after we add an independent random variable as a common cause to the dataset? (<strong>Add Random Common Cause</strong>)</li>
</ul>
<p>For all 3 - Hint: It should not.</p>
<p>For these tests to indicate that our results are valid, in their outputs they should all: * Give an ‘Estimated Effect’ that is close to the ‘New Effect’ (that they compute under these changes), &amp; * Give a large p-value, greater than 0.05, meaning: no statistically significant difference between the estimated and the new effects</p>
<div id="cc072b32-3f37-422d-aad3-1b34fc308236" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.878637Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.878292Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:39:41.915902Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:39:41.914328Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.878586Z&quot;}" data-tags="[]" data-execution_count="27">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Refute estimate</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>refutation_list<span class="op">=</span> []</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>inspect_refutations <span class="op">=</span> <span class="va">True</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>refuter_list <span class="op">=</span> [<span class="st">"bootstrap_refuter"</span>, <span class="st">"data_subset_refuter"</span>, <span class="st">"random_common_cause"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="56c02290-1e0d-499f-87e8-cf0619b0a234" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:39:41.922091Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:39:41.921718Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:40:04.121769Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:40:04.118050Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:39:41.922044Z&quot;}" data-tags="[]" data-execution_count="28">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>capture</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> refuter <span class="kw">in</span> refuter_list:</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    ref <span class="op">=</span> model.refute_estimate(estimands, estimate, method_name<span class="op">=</span>refuter)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    refutation_list.append(ref)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fd9c8a45-9180-4cf1-a3e3-244b1a6c01aa" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2023-10-10T17:40:04.124988Z&quot;,&quot;iopub.status.busy&quot;:&quot;2023-10-10T17:40:04.124644Z&quot;,&quot;iopub.status.idle&quot;:&quot;2023-10-10T17:40:04.145198Z&quot;,&quot;shell.execute_reply&quot;:&quot;2023-10-10T17:40:04.142566Z&quot;,&quot;shell.execute_reply.started&quot;:&quot;2023-10-10T17:40:04.124945Z&quot;}" data-tags="[]" data-execution_count="29">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Refutation values</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>refuter_count <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> inspect_refutations <span class="kw">is</span> <span class="va">True</span>:</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> refutation <span class="kw">in</span> refutation_list:</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"####### Refutation </span><span class="sc">{}</span><span class="st">#######################################################################################"</span>.<span class="bu">format</span>(refuter_count))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(refutation)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>        refuter_count <span class="op">+=</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>####### Refutation 1#######################################################################################
Refute: Bootstrap Sample Dataset
Estimated effect:555.9003475909958
New effect:553.3173718006659
p value:1.0

####### Refutation 2#######################################################################################
Refute: Use a subset of data
Estimated effect:555.9003475909958
New effect:552.3741440620961
p value:0.8400000000000001

####### Refutation 3#######################################################################################
Refute: Add a random common cause
Estimated effect:555.9003475909958
New effect:555.9663141143694
p value:0.92
</code></pre>
</div>
</div>
<p>As expected, all 3 refuters find: our estimate is consistent with the data. There is no statistically significant difference between the estimated and the new effects (New and Estimated effect values: very similar; p-values are greater than 0.05).</p>
<p>DoWhy has further refuters. Note: one for <strong>sensitivity analysis</strong> to unmeasured confounders (<code>method_name="add_unobserved_common_cause"</code>): * How much will the effect estimate change, at different levels of unmeasured confounding? E.g. will it still be positive? * This requires the user to parametrise it with assumptions for the maximum possible effect size of an unmeasured confounder, based on domain expertise. * For more, see this example notebook: https://github.com/py-why/dowhy/blob/main/docs/source/example_notebooks/dowhy_simple_example.ipynb</p>
<section id="dagitty-online-tool" class="level3">
<h3 class="anchored" data-anchor-id="dagitty-online-tool">DAGitty online tool</h3>
<p>https://dagitty.net/dags.html#</p>
<p>e.g.&nbsp;click ‘Examples’ at the top, select ‘Extended Confouding Triangle’.</p>
</section>
</section>
</section>
<section id="further-materials" class="level1">
<h1>Further materials</h1>
<p>If you’d like to understand more about these tools, resources to check out next: * DoWhy - user guide: https://www.pywhy.org/dowhy/v0.10.1/user_guide/index.html * DAGitty.net - brief ‘cheat sheet’ guide: https://dagitty.net/learn/primer/Dagitty-Cheat-Sheet.pdf</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>